CREATE DATABASE IF NOT EXISTS aihub_pro DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE aihub_pro;

DROP TABLE IF EXISTS favorite;
DROP TABLE IF EXISTS ai_tool;
DROP TABLE IF EXISTS tool_category;
DROP TABLE IF EXISTS prompt;
DROP TABLE IF EXISTS prompt_category;
DROP TABLE IF EXISTS article;
DROP TABLE IF EXISTS banner;
DROP TABLE IF EXISTS admin;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    nickname VARCHAR(50),
    avatar VARCHAR(255),
    email VARCHAR(100),
    status TINYINT DEFAULT 1 COMMENT '1启用 0禁用',
    role TINYINT DEFAULT 0 COMMENT '0普通用户 1管理员',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

CREATE TABLE admin (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    nickname VARCHAR(50),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='管理员表';

CREATE TABLE tool_category (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    sort INT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工具分类表';

CREATE TABLE ai_tool (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    category_id BIGINT NOT NULL COMMENT '外键关联tool_category',
    name VARCHAR(100) NOT NULL,
    logo VARCHAR(255) COMMENT 'Logo图片URL',
    description VARCHAR(500) COMMENT '简介',
    detail TEXT COMMENT '详细介绍',
    website_url VARCHAR(255) COMMENT '官网地址',
    screenshot VARCHAR(255) COMMENT '截图URL',
    tags VARCHAR(255) COMMENT '标签，逗号分隔',
    is_free TINYINT DEFAULT 1 COMMENT '1免费 0付费',
    rating DECIMAL(2,1) DEFAULT 5.0 COMMENT '推荐指数',
    views INT DEFAULT 0 COMMENT '浏览量',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_tool_category FOREIGN KEY (category_id) REFERENCES tool_category(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI工具表';

CREATE TABLE prompt_category (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    sort INT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='提示词分类表';

CREATE TABLE prompt (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    category_id BIGINT NOT NULL COMMENT '外键关联prompt_category',
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL COMMENT '提示词完整内容',
    model_type VARCHAR(50) COMMENT '适用模型: GPT/Claude/Gemini等',
    description VARCHAR(500) COMMENT '简介',
    usage_tips TEXT COMMENT '使用说明',
    views INT DEFAULT 0,
    likes INT DEFAULT 0,
    create_time DATETIME DEFAULT TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_prompt_category FOREIGN KEY (category_id) REFERENCES prompt_category(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='提示词表';

CREATE TABLE favorite (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL COMMENT '外键关联user',
    target_id BIGINT NOT NULL COMMENT '目标ID',
    target_type VARCHAR(20) NOT NULL COMMENT 'tool或prompt',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_favorite_user FOREIGN KEY (user_id) REFERENCES user(id),
    UNIQUE KEY uk_user_target (user_id, target_id, target_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='收藏表';

CREATE TABLE article (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    cover VARCHAR(255) COMMENT '封面图URL',
    summary VARCHAR(500) COMMENT '摘要',
    content LONGTEXT COMMENT '正文内容，支持HTML',
    views INT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='教程文章表';

CREATE TABLE banner (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    link_url VARCHAR(255),
    sort INT DEFAULT 0,
    status TINYINT DEFAULT 1 COMMENT '1显示 0隐藏',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='轮播图表';
